### ISSUE TITLE
Add Normalizing Constraints

### ISSUE THREAD

**Issue by travishathawayrocket** [travishathaway/crimestats#1]
Population, measure of poverty, number of law enforcement officers employed are just a couple examples of some normalizing constraints we could add to the interface and database.

**Comment by travishathaway** [comment]
I have gathered the data I need for the population counts in Portland Oregon.  I still need to take care that I am only comparing for incidents that actually happened in Portland or else I may need to include other cities populations (Gresham, Canby, etc.).

Next step is to add something on the interface to switch to this Normalizing view and also add disclaimer about where the population numbers were gathered from (U.S. Census estimates).

**Comment by travishathaway** [comment]
I have added population data to the application (2010 census tracts).  For further work on this issue, I will add separate issues for each.
